### PR TITLE
Fix Chinese translation from "Core" to "Classic".

### PR DESCRIPTION
**Pull request by agilewalker**

### CODE REVIEW

**Comment by ahmedbodi** [comment]
If a few people can ACK this i can merge it and it will become part of the current PR in bitcoin classic

**Comment by agilewalker** [comment]
For anyone who reviews this commit, here is the summary of changes: 
bitcoin_zh_CN.ts (Simplified Chinese):  Word "核心"(Core) replaced with "经典"(Classic).
bitcoin_zh_TW.ts (Traditional Chinese): Word "核心"(Core) replaced with "經典"(Classic).

**Comment by PartTimeLegend** [comment]
ACK

**Comment by jtoomim** [comment]
The translation looks right to me, but let me see if I can find someone whose Chinese is better than mine...

**Comment by jtoomim** [comment]
screen shot 2016-01-19 at 11 26 47 pm

**Comment by jtoomim** [comment]
ACK.

**Pull request merged**
